version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build-client
          command: ./build-for-local.sh
          working_directory: client
      - run:
          name: build-server
          command: ./build-for-local.sh
          working_directory: server
      - run:
          name: start-database
          command: docker run --name mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=eco -e MYSQL_USER=user -e MYSQL_PASSWORD=password -p 3310:3306 -d mysql:5.7
          working_directory: server
      - run:
          name: create-network
          command: docker network create eco
          working_directory: client
      - run:
          name: start-client
          command: ./deploy-for-local.sh
          working_directory: client
      - run:
          name: start-server
          command: ./deploy-for-local.sh
          working_directory: server
      - run:
          name: install-test-dependencies
          command: npm install
          working_directory: acceptance_tests
      - run:
          name: acceptance-tests
          command: npm run e2e
          working_directory: acceptance_tests