version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
          working_directory: client
      - run:
          name: tests
          command: npm test
          working_directory: client
      - run:
          name: install-dependencies
          command: npm install
          working_directory: server
      - run:
          name: tests
          command: npm test
          working_directory: server
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: docker build -t company/app:$CIRCLE_BRANCH .
          working_directory: client

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build