version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
#      - run:
#          name: install-dependencies
#          command: npm install
#          working_directory: client
#      - run:
#          name: tests
#          command: npm test
#          working_directory: client