version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
          working_directory: client
      - run:
          name: tests
          command: npm test
          working_directory: client
      - run:
          name: install-dependencies
          command: npm install
          working_directory: server
      - run:
          name: tests
          command: npm test
          working_directory: server
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: docker build -t birse/client:$CIRCLE_BRANCH .
          working_directory: client
      - run:
          name: build
          command: docker build -t birse/server:$CIRCLE_BRANCH .
          working_directory: server
  deploy:
    machine: true
    steps:
      - run:
          name: start-database
          command: docker run --name mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=eco -e MYSQL_USER=user -e MYSQL_PASSWORD=password -p 3310:3306 -d mysql:5.7
          working_directory: server
      - run:
          name: start-server
          command: docker run --name server -e DATABASE_HOST=mysql -p 5000:5000 --link mysql -d  birse/server:$CIRCLE_BRANCH
          working_directory: server
      - run:
          name: start-client
          command: docker run --name client -p 3000:3000 -d birse/server:$CIRCLE_BRANCH
          working_directory: server

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build