apiVersion: apps/v1
kind: Deployment
metadata:
  name: eco-ideas-client
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: eco-ideas-client
  template:
    metadata:
      labels:
        app: eco-ideas-client
    spec:
      containers:
        - name: eco-ideas-client
          image: gcr.io/eco-ideas/client:latest
          env:
            - name: REACT_APP_SERVER_HOST
              value: "IP ADDRESS"
            - name: REACT_APP_SERVER_PORT
              value: "5000"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 8
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 3